spring:
  datasource:
    username: root
    password: root
#    url: jdbc:mysql://192.168.31.128:3306/mybatis  #docker镜像
    url: jdbc:mysql://127.0.0.1:3306/shiro  #本地
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#   schema:
#     - classpath:sql/schema.sql
#   initialization-mode: always
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    # 配置监控统计的filters，去掉后监控界面sql无法统计，‘wall’用于防火墙
    filters: wall,stat
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
